# Generated by Django 5.0.1 on 2024-01-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enlace',
            old_name='short_url',
            new_name='url_acortado',
        ),
        migrations.RenameField(
            model_name='enlace',
            old_name='original_url',
            new_name='url_original',
        ),
    ]
