# Generated by Django 5.0.1 on 2024-01-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0002_rename_short_url_enlace_url_acortado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='url_acortado',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
