# Generated by Django 5.0.1 on 2024-01-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0004_enlace_clics_totales_enlace_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='url_personalizado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enlace',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
